language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
     -CC_TEST_REPORTER_ID=222380ea6a65d2b7f400995cadb2abfe6ce094fc39af23482b853600eb670c38
     - NODE_ENV=test
script:
  -npm run coveralls
  -npm run coverage
after_script: 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT